const BASE_INVENTORY = [
  {
    title: '2021 Freightliner Cascadia FT125SLP',
    type: 'Truck',
    brand: 'Freightliner',
    model: 'Cascadia FT125SLP',
    year: 2021,
    price: 29500,
    mileage: 729771,
    state: 'CA',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '1FUJHHDR1LLKS7083',
    rep: 'CTTS',
    location: 'CA'
  },
  {
    title: '2016 Kenworth T880',
    type: 'Truck',
    brand: 'Kenworth',
    model: 'T880',
    year: 2016,
    price: 78700,
    mileage: 77836,
    state: 'GA',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '1XKDDP9X5GJ463782',
    rep: 'CTTS',
    location: 'GA'
  },
  {
    title: '2011 International Prostar',
    type: 'Truck',
    brand: 'International',
    model: 'Prostar',
    year: 2011,
    price: 29500,
    mileage: 728375,
    state: 'TX',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '3HSDJSJNXBN421820',
    rep: 'CTTS',
    location: 'TX'
  },
  {
    title: '2016 Kenworth T880',
    type: 'Truck',
    brand: 'Kenworth',
    model: 'T880',
    year: 2016,
    price: 67200,
    mileage: 447797,
    state: 'FL',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '1NKDXPBX8GJ443755',
    rep: 'CTTS',
    location: 'FL'
  },
  {
    title: '2016 Kenworth T680 Sleeper Truck',
    type: 'Truck',
    brand: 'Kenworth',
    model: 'T680 Sleeper Truck',
    year: 2016,
    price: 39400,
    mileage: 708090,
    state: 'TN',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '1XKYDP9X5GJ463964',
    rep: 'CTTS',
    location: 'TN'
  },
  {
    title: '2016 Freightliner Cascadia FT125SLP',
    type: 'Truck',
    brand: 'Freightliner',
    model: 'Cascadia FT125SLP',
    year: 2016,
    price: 29500,
    mileage: 669947,
    state: 'CA',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '3AKJGLD57GSHZ3174',
    rep: 'CTTS',
    location: 'CA'
  },
  {
    title: '2018 Freightliner Cascadia FT125SLP',
    type: 'Truck',
    brand: 'Freightliner',
    model: 'Cascadia FT125SLP',
    year: 2018,
    price: 44800,
    mileage: 646281,
    state: 'AR',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '3AKJGLDRXJSJV6552',
    rep: 'CTTS',
    location: 'AR'
  },
  {
    title: '2016 International Prostar',
    type: 'Truck',
    brand: 'International',
    model: 'Prostar',
    year: 2016,
    price: 29500,
    mileage: 618999,
    state: 'AL',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '3HSDJAPR1GN106358',
    rep: 'CTTS',
    location: 'AL'
  },
  {
    title: '2013 Kenworth T680 Sleeper Truck',
    type: 'Truck',
    brand: 'Kenworth',
    model: 'T680 Sleeper Truck',
    year: 2013,
    price: 32800,
    mileage: 615039,
    state: 'OH',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '1XKAD29X2DJ364792',
    rep: 'IAA',
    location: 'OH'
  },
  {
    title: '2001 Mack CH613',
    type: 'Truck',
    brand: 'Mack',
    model: 'CH613',
    year: 2001,
    price: 15560,
    mileage: 560000,
    state: 'TX',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '1M2P267C51M047405',
    rep: 'IAA',
    location: 'TX'
  },
  {
    title: '2017 International Prostar',
    type: 'Truck',
    brand: 'International',
    model: 'Prostar',
    year: 2017,
    price: 37200,
    mileage: 534234,
    state: 'VA',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '3HSDJAPR3HN510187',
    rep: 'CTTS',
    location: 'VA'
  },
  {
    title: '2019 International LT625',
    type: 'Truck',
    brand: 'International',
    model: 'LT625',
    year: 2019,
    price: 37200,
    mileage: 486459,
    state: 'TX',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '3HSDZAPR9KN921980',
    rep: 'CTTS',
    location: 'TX'
  },
  {
    title: '2014 Freightliner Cascadia FT125SLP',
    type: 'Truck',
    brand: 'Freightliner',
    model: 'Cascadia FT125SLP',
    year: 2014,
    price: 28250,
    mileage: 480622,
    state: 'TN',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '3AKJGLD59ESFS9745',
    rep: 'Copart',
    location: 'TN'
  },
  {
    title: '2014 Freightliner Cascadia FT125SLP',
    type: 'Truck',
    brand: 'Freightliner',
    model: 'Cascadia FT125SLP',
    year: 2014,
    price: 29500,
    mileage: 469777,
    state: 'NV',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '1FUJGLDV0ELFD1390',
    rep: 'CTTS',
    location: 'NV'
  },
  {
    title: '2014 Freightliner Cascadia FT125SLP',
    type: 'Truck',
    brand: 'Freightliner',
    model: 'Cascadia FT125SLP',
    year: 2014,
    price: 28250,
    mileage: 458183,
    state: 'TN',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '3AKJGLD55ESFU9482',
    rep: 'CTTS',
    location: 'TN'
  },
  {
    title: '2015 International ProStar',
    type: 'Truck',
    brand: 'International',
    model: 'ProStar',
    year: 2015,
    price: 29500,
    mileage: 441488,
    state: 'CO',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '3HSDJAPR5FN607571',
    rep: 'CTTS',
    location: 'CO'
  },
  {
    title: '2013 Volvo VNL64T',
    type: 'Truck',
    brand: 'Volvo',
    model: 'VNL64T',
    year: 2013,
    price: 26000,
    mileage: 611872,
    state: 'NJ',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '4V4NC9EH4DN135570',
    rep: 'IAA',
    location: 'NJ'
  },
  {
    title: '2016 Volvo VNL64T',
    type: 'Truck',
    brand: 'Volvo',
    model: 'VNL64T',
    year: 2016,
    price: 31000,
    mileage: 399999,
    state: 'IL',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '4V4NC9EH7GN968675',
    rep: 'CTTS',
    location: 'IL'
  },
  {
    title: '2016 International Prostar',
    type: 'Truck',
    brand: 'International',
    model: 'Prostar',
    year: 2016,
    price: 29500,
    mileage: 394014,
    state: 'MA',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '3HSDJAPR5GN106294',
    rep: 'CTTS',
    location: 'MA'
  },
  {
    title: '2016 Kenworth Sleeper Truck',
    type: 'Truck',
    brand: 'Kenworth',
    model: 'Sleeper Truck',
    year: 2016,
    price: 39400,
    mileage: 336751,
    state: 'CA',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '1XKYD49X0GJ474120',
    rep: 'CTTS',
    location: 'CA'
  },
  {
    title: '2016 Volvo VNL64T',
    type: 'Truck',
    brand: 'Volvo',
    model: 'VNL64T',
    year: 2016,
    price: 34100,
    mileage: 319612,
    state: 'TX',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '4V4NC9EJ3GN949920',
    rep: 'CTTS',
    location: 'TX'
  },
  {
    title: '2013 Freightliner Cascadia',
    type: 'Truck',
    brand: 'Freightliner',
    model: 'Cascadia',
    year: 2013,
    price: 0,
    mileage: 336225,
    state: 'CA',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '3AKJGLBG0DSFU9299',
    rep: 'CTTS',
    location: 'CA'
  },
  {
    title: '2013 Freightliner Cascadia',
    type: 'Truck',
    brand: 'Freightliner',
    model: 'Cascadia',
    year: 2013,
    price: 0,
    mileage: 146705,
    state: 'CA',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '3AKJGLDV9DSBJ3753',
    rep: 'CTTS',
    location: 'CA'
  },
  {
    title: '2014 International TerraStar',
    type: 'Truck',
    brand: 'International',
    model: 'TerraStar',
    year: 2014,
    price: 0,
    mileage: 0,
    state: 'CA',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '3HAMMMMM1EL770410',
    rep: 'CTTS',
    location: 'CA'
  },
  {
    title: '2019 Peterbilt Sleeper Truck',
    type: 'Truck',
    brand: 'Peterbilt',
    model: 'Sleeper Truck',
    year: 2019,
    price: 39400,
    mileage: 664545,
    state: 'FL',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '1NPBD49X7KD232764',
    rep: 'Remarkete place',
    location: 'FL'
  },
  {
    title: '2016 Kenworth Sleeper Truck',
    type: 'Truck',
    brand: 'Kenworth',
    model: 'Sleeper Truck',
    year: 2016,
    price: 39400,
    mileage: 644737,
    state: 'CA',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '1XKYD49X9GJ494772',
    rep: 'CTTS',
    location: 'CA'
  },
  {
    title: '2014 Freightliner Sleeper Truck',
    type: 'Truck',
    brand: 'Freightliner',
    model: 'Sleeper Truck',
    year: 2014,
    price: 28250,
    mileage: 458183,
    state: 'TN',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '3AKJGLD5XESFS9307',
    rep: 'CTTS',
    location: 'TN'
  },
  {
    title: '2015 Peterbilt 389',
    type: 'Truck',
    brand: 'Peterbilt',
    model: '389',
    year: 2015,
    price: 36480,
    mileage: 529920,
    state: 'GA',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '1XPBDB9X7FD287357',
    rep: 'Remarkete place',
    location: 'GA'
  },
  {
    title: '2016 Peterbilt Sleeper Truck',
    type: 'Truck',
    brand: 'Peterbilt',
    model: 'Sleeper Truck',
    year: 2016,
    price: 39400,
    mileage: 658966,
    state: 'NV',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '1XPBD49X7GD356631',
    rep: 'CTTS',
    location: 'NV'
  },
  {
    title: '2017 Peterbilt Sleeper Truck',
    type: 'Truck',
    brand: 'Peterbilt',
    model: 'Sleeper Truck',
    year: 2017,
    price: 39400,
    mileage: 561936,
    state: 'NV',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '1XPBD49XXHD401380',
    rep: 'CTTS',
    location: 'NV'
  },
  {
    title: '2013 Freightliner Cascadia FT125SLP',
    type: 'Truck',
    brand: 'Freightliner',
    model: 'Cascadia FT125SLP',
    year: 2013,
    price: 0,
    mileage: 132344,
    state: 'CA',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '3AKJGLDR3DSBS2767',
    rep: 'CTTS',
    location: 'CA'
  },
  {
    title: '2017 Kenworth Sleeper Truck',
    type: 'Truck',
    brand: 'Kenworth',
    model: 'Sleeper Truck',
    year: 2017,
    price: 39400,
    mileage: 381800,
    state: 'NJ',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '1XKYD49X9HJ117680',
    rep: 'Remarkete place',
    location: 'NJ'
  },
  {
    title: '2016 Peterbilt Sleeper Truck',
    type: 'Truck',
    brand: 'Peterbilt',
    model: 'Sleeper Truck',
    year: 2016,
    price: 39400,
    mileage: 633806,
    state: 'TN',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '1XPBD49X0GD336287',
    rep: 'CTTS',
    location: 'TN'
  },
  {
    title: '2016 Peterbilt 579',
    type: 'Truck',
    brand: 'Peterbilt',
    model: '579',
    year: 2016,
    price: 39400,
    mileage: 761233,
    state: 'TN',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '1XPBDP9X8GD330978',
    rep: 'CTTS',
    location: 'TN'
  },
  {
    title: '2016 Peterbilt 389',
    type: 'Truck',
    brand: 'Peterbilt',
    model: '389',
    year: 2016,
    price: 39400,
    mileage: 577492,
    state: 'NV',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '1XPBDB9X7GD297979',
    rep: 'CTTS',
    location: 'NV'
  },
  {
    title: '2020 Volvo VNL760',
    type: 'Truck',
    brand: 'Volvo',
    model: 'VNL760',
    year: 2020,
    price: 84500,
    mileage: 412880,
    state: 'WA',
    status: 'Available',
    dealStatus: 'Open',
    vin: '4V4NC9EH0LN876543',
    rep: 'MT',
    location: 'WA'
  },
  {
    title: '2022 Peterbilt 579 Ultraloft',
    type: 'Truck',
    brand: 'Peterbilt',
    model: '579 Ultraloft',
    year: 2022,
    price: 118900,
    mileage: 186200,
    state: 'NJ',
    status: 'Available',
    dealStatus: 'Open',
    vin: '1XPBDP9X2ND785410',
    rep: 'MT',
    location: 'NJ'
  },
  {
    title: '2019 Freightliner M2 106 Box Truck',
    type: 'Truck',
    brand: 'Freightliner',
    model: 'M2 106 Box',
    year: 2019,
    price: 65900,
    mileage: 298440,
    state: 'IL',
    status: 'Available',
    dealStatus: 'Open',
    vin: '1FVACWFC1KHLP3321',
    rep: 'MT',
    location: 'IL'
  },
  {
    title: '2021 Kenworth T680 Next Gen',
    type: 'Truck',
    brand: 'Kenworth',
    model: 'T680 Next Gen',
    year: 2021,
    price: 109500,
    mileage: 265900,
    state: 'MO',
    status: 'Available',
    dealStatus: 'Open',
    vin: '1XKYD49X0MJ423876',
    rep: 'MT',
    location: 'MO'
  },
  {
    title: '2018 International LT625 Sleeper',
    type: 'Truck',
    brand: 'International',
    model: 'LT625 Sleeper',
    year: 2018,
    price: 52400,
    mileage: 502000,
    state: 'IN',
    status: 'Available',
    dealStatus: 'Open',
    vin: '3HSDZAPR8JN234987',
    rep: 'MT',
    location: 'IN'
  },
  {
    title: '2023 Utility 3000R Reefer Trailer',
    type: 'Trailer',
    brand: 'Utility',
    model: '3000R Reefer',
    year: 2023,
    price: 78900,
    mileage: 12000,
    state: 'FL',
    status: 'Available',
    dealStatus: 'Open',
    vin: '1UYVS2535P3004590',
    rep: 'CTTS',
    location: 'FL'
  },
  {
    title: '2020 Vanguard Dry Van Trailer',
    type: 'Trailer',
    brand: 'Vanguard',
    model: 'Dry Van',
    year: 2020,
    price: 34950,
    mileage: 15500,
    state: 'OH',
    status: 'Available',
    dealStatus: 'Open',
    vin: '5V8VC5325LT209876',
    rep: 'IAA',
    location: 'OH'
  },
  {
    title: '2019 Delucio Flatbed Trailer',
    type: 'Trailer',
    brand: 'Delucio',
    model: 'Flatbed',
    year: 2019,
    price: 28900,
    mileage: 22400,
    state: 'MS',
    status: 'Available',
    dealStatus: 'Open',
    vin: '7D2BE4025KM123450',
    rep: 'MT',
    location: 'MS'
  },
  {
    title: '2022 Freightliner Cascadia 126',
    type: 'Truck',
    brand: 'Freightliner',
    model: 'Cascadia 126',
    year: 2022,
    price: 102500,
    mileage: 198345,
    state: 'PA',
    status: 'Available',
    dealStatus: 'Open',
    vin: '3AKJHHDR5NSME2450',
    rep: 'CTTS',
    location: 'PA'
  },
  {
    title: '2018 Peterbilt 389 Long Hood',
    type: 'Truck',
    brand: 'Peterbilt',
    model: '389 Long Hood',
    year: 2018,
    price: 97400,
    mileage: 432100,
    state: 'OK',
    status: 'Available',
    dealStatus: 'Open',
    vin: '1NPXLP9X0JD485012',
    rep: 'MT',
    location: 'OK'
  },
  {
    title: '2015 Volvo VNL670',
    type: 'Truck',
    brand: 'Volvo',
    model: 'VNL670',
    year: 2015,
    price: 41900,
    mileage: 643220,
    state: 'NC',
    status: 'Available',
    dealStatus: 'Open',
    vin: '4V4NC9EH2FN912340',
    rep: 'CTTS',
    location: 'NC'
  },
  {
    title: '2021 Kenworth W990',
    type: 'Truck',
    brand: 'Kenworth',
    model: 'W990',
    year: 2021,
    price: 128400,
    mileage: 174500,
    state: 'UT',
    status: 'Available',
    dealStatus: 'Open',
    vin: '1NKZL49X0MJ205678',
    rep: 'CTTS',
    location: 'UT'
  },
  {
    title: '2019 International MV607 Box Truck',
    type: 'Truck',
    brand: 'International',
    model: 'MV607 Box Truck',
    year: 2019,
    price: 58900,
    mileage: 256880,
    state: 'CO',
    status: 'Available',
    dealStatus: 'Open',
    vin: '3HAEUMML9KL248901',
    rep: 'IAA',
    location: 'CO'
  },
  {
    title: '2020 Utility Curtain Side Trailer',
    type: 'Trailer',
    brand: 'Utility',
    model: 'Curtain Side',
    year: 2020,
    price: 45500,
    mileage: 18000,
    state: 'GA',
    status: 'Available',
    dealStatus: 'Open',
    vin: '1UYCS2530L1009876',
    rep: 'MT',
    location: 'GA'
  },
  {
    title: '2018 Vanguard Reefer Trailer',
    type: 'Trailer',
    brand: 'Vanguard',
    model: 'Reefer',
    year: 2018,
    price: 36500,
    mileage: 40200,
    state: 'SC',
    status: 'Available',
    dealStatus: 'Open',
    vin: '5V8VC5323JT204578',
    rep: 'CTTS',
    location: 'SC'
  },
  {
    title: '2022 Peterbilt 579 UltraLoft',
    type: 'Truck',
    brand: 'Peterbilt',
    model: '579 UltraLoft',
    year: 2022,
    price: 128500,
    mileage: 184200,
    state: 'TX',
    status: 'Sold',
    dealStatus: 'Closed',
    vin: '1XPBDP9X0ND789123',
    rep: 'CTTS',
    location: 'TX'
  },
  {
    title: '2021 Volvo VNL760 Sleeper',
    type: 'Truck',
    brand: 'Volvo',
    model: 'VNL760 Sleeper',
    year: 2021,
    price: 114900,
    mileage: 201400,
    state: 'GA',
    status: 'Sold',
    dealStatus: 'Closed',
    vin: '4V4NC9EJ9MN123654',
    rep: 'IAA',
    location: 'GA'
  },
  {
    title: '2019 Freightliner Cascadia Day Cab',
    type: 'Truck',
    brand: 'Freightliner',
    model: 'Cascadia Day Cab',
    year: 2019,
    price: 76500,
    mileage: 342110,
    state: 'IL',
    status: 'Sold',
    dealStatus: 'Closed',
    vin: '3AKJGLD59KSKL8821',
    rep: 'MT',
    location: 'IL'
  },
  {
    title: '2018 Kenworth T680 Day Cab',
    type: 'Truck',
    brand: 'Kenworth',
    model: 'T680 Day Cab',
    year: 2018,
    price: 68900,
    mileage: 415778,
    state: 'OK',
    status: 'Sold',
    dealStatus: 'Closed',
    vin: '1XKYD49X7JJ234567',
    rep: 'CTTS',
    location: 'OK'
  },
  {
    title: '2020 International HX620 Dump Truck',
    type: 'Truck',
    brand: 'International',
    model: 'HX620 Dump Truck',
    year: 2020,
    price: 134500,
    mileage: 158990,
    state: 'PA',
    status: 'Sold',
    dealStatus: 'Closed',
    vin: '1HTXHAPT0LH764321',
    rep: 'CTTS',
    location: 'PA'
  },
  {
    title: '2021 Mack Anthem 64T',
    type: 'Truck',
    brand: 'Mack',
    model: 'Anthem 64T',
    year: 2021,
    price: 99950,
    mileage: 276540,
    state: 'NC',
    status: 'Sold',
    dealStatus: 'Closed',
    vin: '1M1AN4GY8MM025789',
    rep: 'IAA',
    location: 'NC'
  },
  {
    title: '2017 Great Dane Champion Dry Van',
    type: 'Trailer',
    brand: 'Great Dane',
    model: 'Champion Dry Van',
    year: 2017,
    price: 24500,
    mileage: 11200,
    state: 'IN',
    status: 'Sold',
    dealStatus: 'Closed',
    vin: '1GR1A0624HJ304560',
    rep: 'Copart',
    location: 'IN'
  },
  {
    title: '2020 Wabash ArcticLite Reefer',
    type: 'Trailer',
    brand: 'Wabash',
    model: 'ArcticLite Reefer',
    year: 2020,
    price: 53800,
    mileage: 8900,
    state: 'WI',
    status: 'Sold',
    dealStatus: 'Closed',
    vin: '1JJV532D5LL279845',
    rep: 'CTTS',
    location: 'WI'
  },
  {
    title: '2022 Fontaine Infinity Flatbed',
    type: 'Trailer',
    brand: 'Fontaine',
    model: 'Infinity Flatbed',
    year: 2022,
    price: 46800,
    mileage: 7200,
    state: 'AL',
    status: 'Sold',
    dealStatus: 'Closed',
    vin: '13N2482C2N1532098',
    rep: 'MT',
    location: 'AL'
  },
  {
    title: '2023 Utility 4000DX Dry Van',
    type: 'Trailer',
    brand: 'Utility',
    model: '4000DX Dry Van',
    year: 2023,
    price: 52900,
    mileage: 3500,
    state: 'NJ',
    status: 'Sold',
    dealStatus: 'Closed',
    vin: '1UYVS2535P3901245',
    rep: 'CTTS',
    location: 'NJ'
  }
];

const ENGINE_OPTIONS = [
  'Detroit DD15 / 505 HP',
  'Cummins X15 / 500 HP',
  'Volvo D13 / 455 HP',
  'PACCAR MX-13 / 455 HP',
  'Cummins ISX15 / 450 HP',
  'Detroit DD13 / 470 HP',
  'Volvo D11 / 405 HP',
  'PACCAR MX-11 / 430 HP',
  'Cummins X12 / 455 HP',
  'International A26 / 475 HP'
];

const TRANSMISSION_OPTIONS = [
  '12-speed automatic',
  '10-speed manual',
  '13-speed manual',
  '18-speed manual',
  'Endurant 12-speed auto',
  'Allison 6-speed automatic'
];

const LOCATION_BANK = [
  { city: 'Los Angeles', state: 'CA' },
  { city: 'Dallas', state: 'TX' },
  { city: 'Atlanta', state: 'GA' },
  { city: 'Chicago', state: 'IL' },
  { city: 'Phoenix', state: 'AZ' },
  { city: 'Philadelphia', state: 'PA' },
  { city: 'Orlando', state: 'FL' },
  { city: 'Salt Lake City', state: 'UT' },
  { city: 'Nashville', state: 'TN' },
  { city: 'Kansas City', state: 'MO' }
];

const PHONE_BANK = [
  '+1 (310) 555-0147',
  '+1 (972) 555-0188',
  '+1 (470) 555-0114',
  '+1 (773) 555-0106',
  '+1 (602) 555-0199',
  '+1 (215) 555-0132',
  '+1 (407) 555-0121',
  '+1 (385) 555-0155',
  '+1 (629) 555-0178',
  '+1 (816) 555-0166'
];

const FEATURE_LIBRARY = [
  ['Sleeper cab', 'APU', 'Aluminum wheels', 'Full aero kit'],
  ['Collision mitigation', 'Lane assist', 'Disc brakes all around'],
  ['Fresh PM service', 'Clean title', 'No active faults'],
  ['New drive tires', 'DOT ready', 'Maintenance records'],
  ['Thermo King APU', 'Bunk heater', 'Fridge & inverter'],
  ['Alloy wheels', 'Air ride suspension', 'Fresh detail'],
  ['Sliding tandems', 'Air ride', 'Steel frame'],
  ['Logistics posts', 'Aluminum roof', 'Translucent roof'],
  ['Scale certified', 'E-logs ready', 'Bluetooth audio'],
  ['Fresh brakes', 'LED lighting', 'Recent alignment']
];

const FALLBACK_IMAGES = [
  'https://imagescdn.dealercarsearch.com/Media/22484/23001914/638930206131273528.jpg',
  'https://images.pexels.com/photos/2199293/pexels-photo-2199293.jpeg',
  'https://images.pexels.com/photos/2199294/pexels-photo-2199294.jpeg',
  'https://images.pexels.com/photos/2199295/pexels-photo-2199295.jpeg',
  'https://images.pexels.com/photos/2199296/pexels-photo-2199296.jpeg',
  'https://images.pexels.com/photos/2199297/pexels-photo-2199297.jpeg',
  'https://images.pexels.com/photos/21694/pexels-photo.jpg'
];

const COLOR_PALETTE = ['White','Red','Blue','Black','Silver','Gray','Green','Maroon','Navy','Charcoal'];

function deriveModel(title = '', brand = '') {
  const cleaned = title.replace(/\b(19|20)\d{2}\b/, '').replace(new RegExp(brand, 'i'), '').replace(/\s+/g, ' ').trim();
  return cleaned || 'Model';
}

const INVENTORY_SEED = BASE_INVENTORY.map((unit, idx) => {
  const location = LOCATION_BANK[idx % LOCATION_BANK.length];
  const state = unit.state && unit.state !== 'Unknown' && unit.state !== 'Other' ? unit.state : location.state;
  const color = unit.color && unit.color !== 'Unknown' && unit.color !== 'Other' ? unit.color : COLOR_PALETTE[idx % COLOR_PALETTE.length];
  const primaryImage = unit.image || FALLBACK_IMAGES[idx % FALLBACK_IMAGES.length];
  const baseGallery = Array.isArray(unit.images) ? unit.images.filter(Boolean) : [];
  const gallery = [primaryImage, ...baseGallery, FALLBACK_IMAGES[(idx + 3) % FALLBACK_IMAGES.length]]
    .filter(Boolean)
    .slice(0, 5);
  const description = unit.description || `${unit.year || 'Late-model'} ${unit.brand || ''} ${deriveModel(unit.title, unit.brand)} ready for work with clean title and recent service.`.trim();
  const features = Array.isArray(unit.features) && unit.features.length ? unit.features : FEATURE_LIBRARY[idx % FEATURE_LIBRARY.length];

  return {
    ...unit,
    state,
    color,
    model: unit.model || deriveModel(unit.title, unit.brand),
    engine: unit.engine || ENGINE_OPTIONS[idx % ENGINE_OPTIONS.length],
    transmission: unit.transmission || TRANSMISSION_OPTIONS[idx % TRANSMISSION_OPTIONS.length],
    condition: unit.condition || (idx % 6 === 0 ? 'New' : 'Used'),
    location: unit.location || `${location.city}, ${location.state}`,
    phone: unit.phone || PHONE_BANK[idx % PHONE_BANK.length],
    description,
    features,
    images: [...new Set(gallery)],
    image: gallery[0],
    price: unit.price ?? 0,
    mileage: unit.mileage ?? 0,
    status: unit.status || 'Available'
  };
});

// Expose the seed globally so inline scripts on static pages can access it.
if (typeof globalThis !== 'undefined') {
  globalThis.BASE_INVENTORY = BASE_INVENTORY;
  globalThis.INVENTORY_SEED = INVENTORY_SEED;
}
